spring:
  config:
    activate:
      on-profile: dev

yugabyte:
  datasource:
    url: jdbc:postgresql://us-west-2.1673b1f5-94c4-4590-8466-64c2aec47aea.aws.ybdb.io:5433/ygd_dev
    load-balance: true
    username: admin
    password: M_pU7r4d7M7WcC6MvscwobHWPBxO7h

# Logging
logging.level:
  com.zaxxer.hikari: TRACE
  com.zaxxer.hikari.HikariConfig: DEBUG
  com.yugabyte.data.jdbc: DEBUG
  org.springframework.jdbc.core.JdbcTemplate: DEBUG
  org.springframework.jdbc.core.StatementCreatorUtils: TRACE