spring:
  config:
    activate:
      on-profile: prod

yugabyte:
  datasource:
    url: jdbc:postgresql://us-west-2.1673b1f5-94c4-4590-8466-64c2aec47aea.aws.ybdb.io:5433/ygd_prod
    load-balance: true
    username: admin
    password: M_pU7r4d7M7WcC6MvscwobHWPBxO7h
