spring:
  application:
    name: ygd-api
  profiles:
    active: local

#management:
#  endpoints:
#    web:
#      path
#      base-path: /manage
#      exposure.include: "*"


# Logging
logging.level:
  com.zaxxer.hikari: TRACE
  com.zaxxer.hikari.HikariConfig: DEBUG
  com.yugabyte.data.jdbc: DEBUG
  org.springframework.jdbc.core.JdbcTemplate: DEBUG
  org.springframework.jdbc.core.StatementCreatorUtils: TRACE